services:
  fiesta_app:
    build: ./app
    expose:
      - "8000"             

  fiesta_nginx:
    image: nginx:1.27-alpine
    depends_on:
      - fiesta_app
    ports:
      - "8080:80"           
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro